// songList.js
const songList = [
    { title: 'Yêu người có ước mơ - Bùi Trường Linh', file: 'audio/audio.mp3' },
    { title: 'Pano - Zack Tabudlo', file: 'audio/audio_1.mp3' },
    { title: 'Treo (2am) - The Cassette', file: 'audio/audio_2.mp3'},
    { title: 'Đừng làm trái tim anh đau - Sơn Tùng M-TP', file: 'audio/audio_3.mp3'},
    { title: 'Ngày đẹp trời để nói chia tay - Lou Hoàng', file: 'audio/audio_4.mp3'},
    { title: 'Thích một người - Trung I.U | Piano cover | Nguyenn', file: 'audio/audio_5.mp3'},
    { title: 'Thế giới không còn niềm đau - Khiem', file: 'audio/audio_6.mp3'},
    { title: 'Giờ em là cô dâu - NIT ft Huu Bui', file: 'audio/audio_7.mp3'},
    { title: 'Lựa chọn của em - Buitruonglinh ft. vuphungtien, dautatdat', file: 'audio/audio_8.mp3'},
    { title: 'Em à - Buitruonglinh', file: 'audio/audio_9.mp3'},
    { title: 'Đường tôi chở em về - buitruonglinh', file: 'audio/audio_10.mp3'},
    { title: 'Drive my car - Deamn', file: 'audio/audio_11.mp3'},
    { title: 'Give me your love 8D - (Nightcore) Deamn', file: 'audio/audio_12.mp3'},
    { title: 'Where we started - Lost Sky ft. Jex', file: 'audio/audio_13.mp3'},
    { title: 'Darkside - Alan Walker ft.', file: 'audio/audio_14.mp3'},
    { title: 'Chàng trai bất tử - Sino ft. An Vũ', file: 'audio/audio_15.mp3'},
    { title: 'Yêu em trong mơ - Sino x Kai x An Vũ', file: 'audio/audio_16.mp3'},
    { title: 'Apollo - Nightcore', file: 'audio/audio_17.mp3'},
    { title: 'Lần cuối - Ngọt', file: 'audio/audio_18.mp3'},
  ];